### ISSUE TITLE
wen eta lazap

### ISSUE THREAD

**Issue by Baggette** [Lazap-Development/lazap-but-rust#3]

**Comment by JayyDoesDev** [comment]
Most likely not for awhile

**Comment by Baggette** [comment]
> Most likely not for awhile

We should blackmail dash

**Comment by LogicApples** [comment]
I agree on your statement

**Comment by Uday-007** [comment]
> I agree on your statement

Ratio + you're white. also This is my first time using this feature :Man:

**Comment by ChopChoP534** [comment]
lazep*

**Comment by face-hh** [comment]
> > I agree on your statement
> 
> Ratio + you're white. also This is my first time using this feature :Man:

Counter ratio + L + hated

**Comment by Baggette** [comment]
> > > I agree on your statement
> > 
> > 
> > Ratio + you're white. also This is my first time using this feature :Man:
> 
> Counter ratio + L + hated

Great argument however ligma

**Comment by DashCruft** [comment]
Please keep this professional.

**Comment by Baggette** [comment]
> Please keep this professional.

ok but make lazap come out faster smh 🙄

**Comment by face-hh** [comment]
> > > > I agree on your statement
> > > 
> > > 
> > > Ratio + you're white. also This is my first time using this feature :Man:
> > 
> > 
> > Counter ratio + L + hated
> 
> Great argument however ligma

ligma balls in yo mouth + L + you french bread

**Comment by LogicApples** [comment]
I must agree

**Comment by Assassin-1234** [comment]
balls indeed
